import {
  GeolocateControl,
  Map as MapLibreMap,
  Marker,
  NavigationControl,
  ScaleControl,
  type GeoJSONSource,
  type MapLayerMouseEvent,
} from 'maplibre-gl';
import type { FeatureCollection } from 'geojson';
import 'maplibre-gl/dist/maplibre-gl.css';
import { useEffect, useRef, useState } from 'react';
import { api } from '../api/client';
import type { LngLatPoint, RouteFeature } from '../api/types';
import { config } from '../config';
import {
  pathColorExpression,
  pathOpacityExpression,
  pathSortKeyExpression,
  pathWidthExpression,
  type ColorMode,
} from './pathStyle';
import './setupMapLibre';

export interface HoveredPath {
  name: string | null;
  source: 'vic_dtp_bin' | 'osm' | null;
  infraCategory: string;
  highwayType: string | null;
  widthM: number | null;
  hazards: string;
  surface: string | null;
  surfaceClass: string | null;
  surfaceInferred: boolean;
  smoothness: string | null;
}

const stringProp = (value: unknown): string | null => (typeof value === 'string' && value !== '' ? value : null);

export type Waypoint = 'start' | 'end';

interface MapViewProps {
  colorMode: ColorMode;
  start: LngLatPoint | null;
  end: LngLatPoint | null;
  route: RouteFeature | null;
  onMapClick: (point: LngLatPoint) => void;
  onWaypointMoved: (which: Waypoint, point: LngLatPoint) => void;
  onHoverPath: (path: HoveredPath | null) => void;
}

const PATHS_SOURCE = 'paths';
const PATHS_LAYER = 'paths-line';
const ROUTE_SOURCE = 'route';
const EMPTY_COLLECTION: FeatureCollection = { type: 'FeatureCollection', features: [] };

function createMarker(className: string, label: string): Marker {
  const el = document.createElement('div');
  el.className = `waypoint-marker ${className}`;
  el.textContent = label;
  return new Marker({ element: el, draggable: true });
}

export function MapView({ colorMode, start, end, route, onMapClick, onWaypointMoved, onHoverPath }: MapViewProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const mapRef = useRef<MapLibreMap | null>(null);
  const markersRef = useRef<Record<Waypoint, Marker | null>>({ start: null, end: null });
  const [loaded, setLoaded] = useState(false);
  // The style is created once; later mode changes are applied by an effect.
  const initialColorMode = useRef(colorMode);

  // Keep the latest callbacks in a ref so map listeners bound once still call them.
  const callbacks = useRef({ onMapClick, onWaypointMoved, onHoverPath });
  callbacks.current = { onMapClick, onWaypointMoved, onHoverPath };

  // --- create the map once ----------------------------------------------------
  useEffect(() => {
    if (!containerRef.current) return;
    const map = new MapLibreMap({
      container: containerRef.current,
      style: config.mapStyleUrl,
      center: config.initialCenter,
      zoom: config.initialZoom,
      maxBounds: config.maxBounds,
    });
    mapRef.current = map;

    map.addControl(new NavigationControl(), 'top-right');
    map.addControl(new GeolocateControl({ positionOptions: { enableHighAccuracy: true } }), 'top-right');
    map.addControl(new ScaleControl({ unit: 'metric' }), 'bottom-right');

    map.on('load', () => {
      // Real path network, served as vector tiles generated by PostGIS.
      map.addSource(PATHS_SOURCE, {
        type: 'vector',
        tiles: [api.pathTilesUrl()],
        minzoom: 8,
        maxzoom: 16, // overzoomed beyond this; geometry is already full-precision
        attribution:
          'Paths: <a href="https://discover.data.vic.gov.au/dataset/bicycle-infrastructure-network">DTP Bicycle Infrastructure Network</a> and <a href="https://www.openstreetmap.org/copyright">© OpenStreetMap contributors</a> (ODbL)',
      });
      map.addLayer({
        id: PATHS_LAYER,
        type: 'line',
        source: PATHS_SOURCE,
        'source-layer': 'paths',
        layout: { 'line-cap': 'round', 'line-join': 'round', 'line-sort-key': pathSortKeyExpression },
        paint: {
          'line-color': pathColorExpression(initialColorMode.current),
          'line-width': pathWidthExpression,
          'line-opacity': pathOpacityExpression(initialColorMode.current),
        },
      });

      // Planned route, drawn above the network with a white casing.
      map.addSource(ROUTE_SOURCE, { type: 'geojson', data: EMPTY_COLLECTION });
      map.addLayer({
        id: 'route-casing',
        type: 'line',
        source: ROUTE_SOURCE,
        layout: { 'line-cap': 'round', 'line-join': 'round' },
        paint: { 'line-color': '#ffffff', 'line-width': ['interpolate', ['linear'], ['zoom'], 10, 6, 16, 12] },
      });
      map.addLayer({
        id: 'route-line',
        type: 'line',
        source: ROUTE_SOURCE,
        layout: { 'line-cap': 'round', 'line-join': 'round' },
        paint: { 'line-color': '#e6007e', 'line-width': ['interpolate', ['linear'], ['zoom'], 10, 3.5, 16, 7] },
      });

      setLoaded(true);
    });

    map.on('click', (event) => {
      callbacks.current.onMapClick({ lng: event.lngLat.lng, lat: event.lngLat.lat });
    });

    map.on('mousemove', PATHS_LAYER, (event: MapLayerMouseEvent) => {
      map.getCanvas().style.cursor = 'crosshair';
      const props = event.features?.[0]?.properties;
      if (!props) return;
      const source = stringProp(props.source);
      callbacks.current.onHoverPath({
        name: stringProp(props.name),
        source: source === 'vic_dtp_bin' || source === 'osm' ? source : null,
        infraCategory: String(props.infra_category ?? 'unknown'),
        highwayType: stringProp(props.highway_type),
        widthM: typeof props.width_m === 'number' ? props.width_m : null,
        hazards: String(props.hazards ?? ''),
        surface: stringProp(props.surface),
        surfaceClass: stringProp(props.surface_class),
        surfaceInferred: props.surface_inferred === true,
        smoothness: stringProp(props.smoothness),
      });
    });
    map.on('mouseleave', PATHS_LAYER, () => {
      map.getCanvas().style.cursor = '';
      callbacks.current.onHoverPath(null);
    });

    return () => {
      map.remove();
      mapRef.current = null;
      markersRef.current = { start: null, end: null };
    };
  }, []);

  // --- sync waypoint markers ---------------------------------------------------
  useEffect(() => {
    const map = mapRef.current;
    if (!map) return;
    const sync = (which: Waypoint, point: LngLatPoint | null, className: string, label: string) => {
      let marker = markersRef.current[which];
      if (!point) {
        marker?.remove();
        markersRef.current[which] = null;
        return;
      }
      if (!marker) {
        marker = createMarker(className, label);
        marker.on('dragend', () => {
          const { lng, lat } = marker!.getLngLat();
          callbacks.current.onWaypointMoved(which, { lng, lat });
        });
        marker.setLngLat(point).addTo(map);
        markersRef.current[which] = marker;
      } else {
        marker.setLngLat(point);
      }
    };
    sync('start', start, 'waypoint-start', 'A');
    sync('end', end, 'waypoint-end', 'B');
  }, [start, end]);

  // --- restyle paths when the colour mode changes ---------------------------------
  useEffect(() => {
    const map = mapRef.current;
    if (!map || !loaded) return;
    map.setPaintProperty(PATHS_LAYER, 'line-color', pathColorExpression(colorMode));
    map.setPaintProperty(PATHS_LAYER, 'line-opacity', pathOpacityExpression(colorMode));
  }, [colorMode, loaded]);

  // --- sync route line ---------------------------------------------------------
  useEffect(() => {
    const map = mapRef.current;
    if (!map || !loaded) return;
    const source = map.getSource<GeoJSONSource>(ROUTE_SOURCE);
    source?.setData(route ?? EMPTY_COLLECTION);
  }, [route, loaded]);

  return <div ref={containerRef} className="map" />;
}
